# Site settings
title: Satyam Dubey
author: Satyam Dubey
general_email: dsatyam5302@gmail.com
academic_email: satyam.dubey@jioinstitute.edu.in

description: > 
  Welcome to my personal site! I am passionate about technology, research, and innovation. 
  Here, you'll find my projects, blog posts, and academic work.

baseurl: "/dsatyam09"  # The subpath of your site, e.g., /blog/
url: "https://ys1998.github.io"  # The base hostname & protocol for your site

# Social media links
twitter_username: dsatyam09
twitter_url: "https://twitter.com/dsatyam09"
github_username: dsatyam09
linkedin_username: dsatyam09  # Removed trailing slash for consistency

# Feel free to add other links here; add the corresponding SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title

# Theme (optional, remove if using custom styling)
theme: minima
